openapi: 3.0.1
info:
  title: Dome.am API
  description: Contact form email service for Dome.am website
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://api.dome.am
    description: Production server

paths:
  /send-email:
    post:
      tags:
        - email
      summary: Send contact form email
      description: Sends an email from the contact form to the site administrator
      operationId: sendEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - username
                - message
              properties:
                from:
                  type: string
                  format: email
                  example: "user@example.com"
                  description: Sender's email address
                username:
                  type: string
                  example: "John Doe"
                  description: Sender's name
                message:
                  type: string
                  maxLength: 5000
                  example: "Hello, I would like to learn more about..."
                  description: Message content
                theme:
                  type: string
                  example: "General inquiry"
                  description: Message subject (optional, defaults to "не задано")
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email sent successfully"
                  messageId:
                    type: string
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Error message"
